
name: Deployment with Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sparshsethi15/blogpoint-server .

      - name: Push image to Dockerhub
        run: docker push sparshsethi15/blogpoint-server

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          IMAGE_NAME=sparshsethi15/blogpoint-server
          kubectl --kubeconfig=$KUBE_CONFIG set image deployment/blogpoint blogpoint=$IMAGE_NAME
          kubectl rollout status deployment/blogpoint

